# Generated by Django 3.1.4 on 2021-02-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('computers', '__first__'),
        ('softwares', '__first__'),
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('source_path', models.CharField(blank=True, max_length=200)),
                ('exec_time', models.TimeField(blank=True, null=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_computer', to='computers.computer')),
                ('exec_days', models.ManyToManyField(blank=True, to='core.Weekday')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BackupMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Backup Methods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('recipient', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TargetDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_path', models.CharField(blank=True, max_length=200)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backups.backup')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.computer')),
            ],
            options={
                'verbose_name_plural': 'Target Devices',
            },
        ),
        migrations.CreateModel(
            name='NotificationFromBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backups.backup')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backups.notification')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backups.notificationtype'),
        ),
        migrations.AddField(
            model_name='backup',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backups.backupmethod'),
        ),
        migrations.AddField(
            model_name='backup',
            name='software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='softwares.software'),
        ),
        migrations.AddField(
            model_name='backup',
            name='target_device',
            field=models.ManyToManyField(blank=True, through='backups.TargetDevice', to='computers.Computer'),
        ),
    ]
