# Generated by Django 3.1.13 on 2021-10-18 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '__first__'),
        ('softwares', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
                ('allocated_space', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='CpuArchitecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'CPU Architectures',
            },
        ),
        migrations.CreateModel(
            name='CpuManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'CPU Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_in_gb', models.IntegerField()),
            ],
            options={
                'ordering': ['disk_type'],
            },
        ),
        migrations.CreateModel(
            name='DiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Types of Disks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GpuManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'GPU Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='RaidType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Types of RAM Modules',
            },
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_in_gb', models.IntegerField()),
                ('ecc', models.BooleanField(default=False)),
                ('ram_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.ramtype')),
            ],
            options={
                'verbose_name_plural': 'RAM Modules',
            },
        ),
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usable_space', models.IntegerField(blank=True, null=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.computer')),
                ('raid_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.raidtype')),
            ],
            options={
                'verbose_name_plural': 'RAIDs in Computer',
            },
        ),
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.gpumanufacturer')),
            ],
            options={
                'verbose_name_plural': 'GPUs',
            },
        ),
        migrations.CreateModel(
            name='DisksInRaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_amount', models.IntegerField()),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.disk')),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.raid')),
            ],
        ),
        migrations.AddField(
            model_name='disk',
            name='disk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.disktype'),
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number_of_cores', models.IntegerField(blank=True, null=True)),
                ('frequency', models.FloatField(blank=True, null=True)),
                ('hyper_threading', models.BooleanField()),
                ('architecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.cpuarchitecture')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.cpumanufacturer')),
            ],
            options={
                'verbose_name_plural': 'CPUs',
            },
        ),
        migrations.CreateModel(
            name='ComputerSoftwareRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='softwares.softwarearchitecture')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.computer')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softwares.software')),
            ],
            options={
                'verbose_name_plural': 'Software on Computer',
            },
        ),
        migrations.CreateModel(
            name='ComputerRamRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.computer')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.ram')),
            ],
            options={
                'verbose_name_plural': 'RAM Modules in Computer',
            },
        ),
        migrations.CreateModel(
            name='ComputerGpuRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.computer')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.gpu')),
            ],
            options={
                'verbose_name_plural': 'GPUs in Computer',
            },
        ),
        migrations.CreateModel(
            name='ComputerDiskRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.computer')),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.disk')),
            ],
            options={
                'verbose_name_plural': 'Disks in Computer',
            },
        ),
        migrations.CreateModel(
            name='ComputerCpuRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.computer')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.cpu')),
            ],
            options={
                'verbose_name_plural': 'CPUs in Computer',
            },
        ),
        migrations.AddField(
            model_name='computer',
            name='cpu',
            field=models.ManyToManyField(through='computers.ComputerCpuRelation', to='computers.Cpu'),
        ),
        migrations.AddField(
            model_name='computer',
            name='disks',
            field=models.ManyToManyField(through='computers.ComputerDiskRelation', to='computers.Disk'),
        ),
        migrations.AddField(
            model_name='computer',
            name='gpu',
            field=models.ManyToManyField(through='computers.ComputerGpuRelation', to='computers.Gpu'),
        ),
        migrations.AddField(
            model_name='computer',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='computers.computer'),
        ),
        migrations.AddField(
            model_name='computer',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='softwares.operatingsystem', verbose_name='OS'),
        ),
        migrations.AddField(
            model_name='computer',
            name='ram',
            field=models.ManyToManyField(through='computers.ComputerRamRelation', to='computers.Ram'),
        ),
        migrations.AddField(
            model_name='computer',
            name='software',
            field=models.ManyToManyField(through='computers.ComputerSoftwareRelation', to='softwares.Software'),
        ),
    ]
