# Generated by Django 3.1.4 on 2021-02-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('softwares', '__first__'),
        ('customers', '0001_initial'),
        ('computers', '0001_initial'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=50, null=True)),
                ('max_allowed_computers', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['software'],
            },
        ),
        migrations.CreateModel(
            name='LicenseWithUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=50, null=True)),
                ('max_allowed_users', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('software', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='softwares.software')),
                ('user', models.ManyToManyField(through='licenses.LicenseWithUser', to='users.User')),
            ],
            options={
                'ordering': ['software'],
            },
        ),
        migrations.AddField(
            model_name='licensewithuser',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licenses.userlicense'),
        ),
        migrations.AddField(
            model_name='licensewithuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.CreateModel(
            name='LicenseWithComputer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computers.computer')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licenses.computerlicense')),
            ],
        ),
        migrations.AddField(
            model_name='computerlicense',
            name='computer',
            field=models.ManyToManyField(through='licenses.LicenseWithComputer', to='computers.Computer'),
        ),
        migrations.AddField(
            model_name='computerlicense',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='computerlicense',
            name='software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='softwares.software'),
        ),
        migrations.AddConstraint(
            model_name='licensewithuser',
            constraint=models.UniqueConstraint(fields=('user', 'license'), name='user per license'),
        ),
        migrations.AddConstraint(
            model_name='licensewithcomputer',
            constraint=models.UniqueConstraint(fields=('computer', 'license'), name='computer per license'),
        ),
    ]
